development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  #database: petdogadmin_development
  database: tinyq_development
  pool: 5
  username: root
  password: root
  #password: ljg1234
  host: 192.168.1.2


production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: tinyq_production
  pool: 5
  username: root
  password: root
  host: localhost

